import './globals.css'
import { FiPlus, FiHelpCircle } from 'react-icons/fi'
import { IoSearch } from 'react-icons/io5'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <div className="fixed left-0 h-screen w-16 md:w-[4.5rem] py-8 flex flex-col items-center justify-between bg-orange-600">
          
          <div className="space-y-4 flex flex-col items-center justify-start">
            <div className="mb-4 w-10 h-10 rounded-full bg-gradient-to-tr from-yellow-600/5 via-yellow-100/70 to-white border-[1px] border-yellow-200/70" />
            <button>
              <IoSearch className="p-1 rounded-full w-8 h-8 text-white hover:bg-white/20 duration-200" />
            </button>
            <button>
              <FiPlus className="p-1 rounded-full w-8 h-8 text-white hover:bg-white/20 duration-200" />
            </button>
          </div>

          <button>
            <FiHelpCircle className="p-1 rounded-full w-8 h-8 text-white hover:bg-white/20 duration-200" />
          </button>

        </div>
        {children}
      </body>
    </html>
  )
}
